Repository nasa/sample_lib, pull requests merged in 2020-05, with the labels that each got.

#22 Integration Candidate: 2020-04-22
  README.md
  fsw/src/sample_lib_version.h
  unit-test/CMakeLists.txt
Labels: IC-20200422

#23 Fix #15, Apply standard style
  fsw/public_inc/sample_lib.h
  fsw/src/sample_lib.c
  fsw/src/sample_lib_internal.h
  fsw/src/sample_lib_version.h
  unit-test/coveragetest/coveragetest_sample_lib.c
  unit-test/coveragetest/sample_lib_coveragetest_common.h
  unit-test/inc/OCS_string.h
  unit-test/override_inc/string.h
  unit-test/override_src/libc_string_stubs.c
  ut-stubs/sample_lib_stubs.c
Labels: CCB - Fast Track, IC-20200520, enhancement

#24 Integration Candidate: 2020-05-20
  README.md
  fsw/public_inc/sample_lib.h
  fsw/src/sample_lib.c
  fsw/src/sample_lib_internal.h
  fsw/src/sample_lib_version.h
  unit-test/coveragetest/coveragetest_sample_lib.c
  unit-test/coveragetest/sample_lib_coveragetest_common.h
  unit-test/inc/OCS_string.h
  unit-test/override_inc/string.h
  unit-test/override_src/libc_string_stubs.c
  ut-stubs/sample_lib_stubs.c
Labels: IC-20200520
